#!/bin/bash
#
# idle_clock_launcher.sh
#
# This file is generated by install.sh — do not edit directly.
# To change IDLE_TIMEOUT_MS or other settings, edit the CONFIG section
# at the top of install.sh and re-run it.
#
# The values below reflect the defaults from install.sh.
# ---------------------------------------------------------------------------
export DISPLAY=:0
export XAUTHORITY=/run/user/1000/gdm/Xauthority

# Dismiss the GNOME Activities overview at login
sleep 5
xdotool key Super

# Idle threshold before clock appears (set by install.sh)
IDLE_MS=60000

while true; do
  idle=$(xprintidle 2>/dev/null || echo 0)

  if [ "$idle" -ge "$IDLE_MS" ]; then
    if ! pgrep -f "$HOME/bin/clock_gtk.py" >/dev/null 2>&1; then
      /usr/bin/python3.11 "$HOME/bin/clock_gtk.py" >/dev/null 2>&1 &
      sleep 1
    fi
  fi

  sleep 2
done